### ISSUE TITLE
render-pipelines canntbe found

### ISSUE THREAD

**Issue by alaxury** [CesiumGS/cesium-unity-samples#28]
project has invalid dependencies: com.unity.render-pipelines.universal@12.17 cannt be found

**Comment by kring** [comment]
What makes you say it's invalid? It's a standard package in the Unity registry:
![image](https://user-images.githubusercontent.com/924374/206444299-36920e34-3741-4db8-8e60-8cbd90968b6d.png)
I'm going to close this because I don't think there's anything to change in Cesium for Unity. But if you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unity/13) and we can help you out.
