### ISSUE TITLE
Confusing about using offline Tileset source

### ISSUE THREAD

**Issue by ruoruoniao** [CesiumGS/cesium-unity-samples#33]
I want to use an offline Tileset, which on LAN, but it doesn't work.
such as: 
![image](https://user-images.githubusercontent.com/37649564/208358497-6f4eb2bd-c67d-4b02-b083-95c999eef0ac.png)
![image](https://user-images.githubusercontent.com/37649564/208358589-660f50a7-4755-4f67-818e-01a465e73615.png)
![image](https://user-images.githubusercontent.com/37649564/208358653-dd51150c-6bf4-414a-a314-5b051ac10519.png)

So how can I use that? Thanks.

**Comment by kring** [comment]
You can't use a TMS server as a Cesium3DTileset, because TMS is just a bunch of images, not a 3D model. Instead, point the Cesium3DTileset at terrain data (such as Cesium World Terrain), and then add a TileMapService raster overlay component and put your TMS URL in there.

Please post further questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13), as we use GitHub issues exclusively for bug reports and feature requests.
